// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoudpGdZz0HxNwpAxatJ9POHLOEDEoTbQ',
    appId: '1:520505771644:web:f316c72fa568808f582bf9',
    messagingSenderId: '520505771644',
    projectId: 'reshot-b706f',
    authDomain: 'reshot-b706f.firebaseapp.com',
    storageBucket: 'reshot-b706f.firebasestorage.app',
    measurementId: 'G-QWSZJ2EVSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpC9ZwGSVtBCs1EBdKNJ0zUihWEmLbXu0',
    appId: '1:520505771644:android:1f439bb622d14af3582bf9',
    messagingSenderId: '520505771644',
    projectId: 'reshot-b706f',
    storageBucket: 'reshot-b706f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsYl1VzizIrIXB-75N9FPLbx-sgcUf8zE',
    appId: '1:520505771644:ios:a3e67133d97d6210582bf9',
    messagingSenderId: '520505771644',
    projectId: 'reshot-b706f',
    storageBucket: 'reshot-b706f.firebasestorage.app',
    iosClientId: '520505771644-oreinfmknn767bki6dldbtqg8ijj1nb1.apps.googleusercontent.com',
    iosBundleId: 'com.reshot.app.reshot',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsYl1VzizIrIXB-75N9FPLbx-sgcUf8zE',
    appId: '1:520505771644:ios:a3e67133d97d6210582bf9',
    messagingSenderId: '520505771644',
    projectId: 'reshot-b706f',
    storageBucket: 'reshot-b706f.firebasestorage.app',
    iosClientId: '520505771644-oreinfmknn767bki6dldbtqg8ijj1nb1.apps.googleusercontent.com',
    iosBundleId: 'com.reshot.app.reshot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoudpGdZz0HxNwpAxatJ9POHLOEDEoTbQ',
    appId: '1:520505771644:web:771ab4ea91f03920582bf9',
    messagingSenderId: '520505771644',
    projectId: 'reshot-b706f',
    authDomain: 'reshot-b706f.firebaseapp.com',
    storageBucket: 'reshot-b706f.firebasestorage.app',
    measurementId: 'G-54C158GSKG',
  );
}
